language: node_js

node_js:
  - 5.5
  - 5.6
  - 5.7

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm i

before_deploy:
  - npm run build

sudo: false

addons:
  firefox: 39.0

deploy:
  provider: heroku
  all_branches: true
  skip_cleanup: true
  api_key:
      secure: ibQhnCqVwsHq2lT1wmU+MoxDLeG1id0UDXN0zOtZBedZRQXv+cb7UxhpfigV/1PKPgLtDOr5nu2wzzS6xX7C7GWtwGXcy0+RjrOTMpXgz/XA5oq1vxCMKGKVI1uMbIEJ5xaVpYWuwlWip1P9BHJurdPi6ASydnDPe1fth6EArm5pcGDKLstrBd9BtS1IgBurldxctYZJjPMpN0UmuOY8Vsx2eyO4uBJq79co57nA3VH4jX1J3vUFhuRE7rXW9Wrv7wiCFVpZGk6DG3LSVZM3amMD2DioJpd4sz/zQXvt6sGUlch88DrOGTJBVZWJwyO17Ja2eIdSDedwvC5cXrtFmPAAYBAFnBYf1cbnbW9B0syMYWoU3xFZd3ChiOOKJdKi9Mzjdz+4fvZxMSB/SB39rag9oGuQksHY+CjP5Itsyuqdk0ponn1sCd/p2lxY1UPeTuMDWf5Pwq7EiWGXLzKqKZV59Nlz16mZ+vMngYE06BqI+nCRLCoFOhBH22DcyGP3wfn0owRF2akqMDznzwPGKeuWMAeI6yD3IiRX1d4thOBlomzHXBEZ0/rX5oI5umIOVK1y6BxoXJdS/KGYrRWKqBECYjheIZw+zzzMZv0y9j49yArq7o2mkGfYr5CHzxnJ8PU/5oTHkSv5SYHzRUuWoCxV6PBOY7nEjgBeDuIjBVI=
  app: dory-app
  on:
    repo: Wildhoney/Dory
