language: node_js

node_js:
  - 4.0
  - 4.1
  - iojs

before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

script:
  - npm i

sudo: false

addons:
  firefox: 39.0

deploy:
  provider: heroku
  app: dory-app
  on:
    repo: Wildhoney/Dory
